// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// 检查环境变量
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = '❌ Supabase 环境变量未配置！\n\n' +
    '请在 Vercel Dashboard 或本地 .env 文件中配置：\n' +
    '- VITE_SUPABASE_URL\n' +
    '- VITE_SUPABASE_PUBLISHABLE_KEY\n\n' +
    '当前状态：\n' +
    `- VITE_SUPABASE_URL: ${SUPABASE_URL ? '✅' : '❌ 缺失'}\n` +
    `- VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY ? '✅' : '❌ 缺失'}`;
  
  console.error(errorMsg);
  
  // 在开发环境下显示警告
  if (import.meta.env.DEV) {
    alert(errorMsg);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 即使环境变量缺失，也创建客户端（避免应用崩溃），但会在调用时失败
// 检查 key 是否是有效的格式
const isValidKey = (key: string) => {
  if (!key || key === 'placeholder-key') return false;
  // Supabase anon key 通常是 JWT token，以 eyJ 开头
  return key.startsWith('eyJ') || key.startsWith('sb_publishable_');
};

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// 验证配置的有效性并在控制台显示调试信息
if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  console.log('🔍 Supabase 配置检查:');
  console.log('  - URL:', SUPABASE_URL);
  console.log('  - Key 前缀:', SUPABASE_PUBLISHABLE_KEY.substring(0, 30) + '...');
  console.log('  - Key 长度:', SUPABASE_PUBLISHABLE_KEY.length);
  console.log('  - URL 格式:', SUPABASE_URL.startsWith('https://') ? '✅' : '❌');
  console.log('  - Key 格式:', isValidKey(SUPABASE_PUBLISHABLE_KEY) ? '✅' : '❌');
  
  if (!SUPABASE_URL.startsWith('https://') || SUPABASE_URL.includes('placeholder')) {
    console.warn('⚠️ VITE_SUPABASE_URL 格式可能不正确:', SUPABASE_URL);
  }
  if (!isValidKey(SUPABASE_PUBLISHABLE_KEY)) {
    console.warn('⚠️ VITE_SUPABASE_PUBLISHABLE_KEY 格式可能不正确。应该是以 "eyJ" 开头的 JWT token 或 "sb_publishable_" 开头的 key');
  }
} else {
  console.error('❌ Supabase 环境变量缺失:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    url: SUPABASE_URL || '未设置',
    keyPrefix: SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...' : '未设置'
  });
}

// 导出配置检查函数
export const isSupabaseConfigured = () => {
  return !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
           !SUPABASE_URL.includes('placeholder') && 
           !SUPABASE_PUBLISHABLE_KEY.includes('placeholder'));
};